### ISSUE TITLE
Free Use

### ISSUE THREAD

**Issue by pkemarco** [stefanfoulis/django-sendsms#37]
Hello everyone. I want to explode the sending of SMS in my future sites and by doing research I came across your API. But I wonder if sending SMS through it can cover the whole world and if it's free, what are the limitations?
Thank you.

**Comment by stefanfoulis** [comment]
Hi @pkemarco 
django-sendsms uses backend services to send out SMS messages. So deliverability and costs depend on those services (e.g https://www.twilio.com/).
