### ISSUE TITLE
Python 2.7 build fail

### ISSUE THREAD

**Issue by endormi** [stefanfoulis/django-sendsms#42]
https://travis-ci.org/stefanfoulis/django-sendsms/jobs/514399325

```
File "/home/travis/build/stefanfoulis/django-sendsms/.eggs/vine-5.0.0a1-py2.7.egg/vine/abstract.py", line 8
    class Thenable(Callable, metaclass=abc.ABCMeta):  # pragma: no cover

SyntaxError: invalid syntax (=)
```

**Comment by endormi** [comment]
What would the solution be? When I pushed the `python 3.7` commit, it worked. I recently just found out about this.

**Comment by pakal** [comment]
On PR https://github.com/stefanfoulis/django-sendsms/pull/43 the python2.7 build succeeds with tox, maybe it was a temporary problem with celery/vine?

**Comment by endormi** [comment]
Yes, I think so.
