### ISSUE TITLE
Use JSON REST API for BulkSMS

### ISSUE THREAD

**Issue by denizdogan** [stefanfoulis/django-sendsms#44]
It seems that this package uses an outdated API for BulkSMS, they now have a new JSON REST API: https://www.bulksms.com/developer/json/v1/

**Comment by denizdogan** [comment]
If you'd accept a PR for this, I'd be willing to implement it, just let me know

**Comment by stefanfoulis** [comment]
Thanks for figuring this out. A PR would be very appreciated.
