### ISSUE TITLE
Tests for python 2.7 are failing -- drop support?

### ISSUE THREAD

**Issue by stefanfoulis** [stefanfoulis/django-sendsms#45]
The python 2.7 tests are failing. It looks like a dependency (probably indirectly through one of the optional dependencies) `more_itertools` does not support python 2.7 anymore (since version `6.0.0`).

Question is:
Should we try to fix this?
Or use this as an opportunity to drop python 2 support?

**Comment by denizdogan** [comment]
According to pipdeptree, this is where it comes from:

```
celery==4.3.0
  - billiard [required: >=3.6.0,<4.0, installed: 3.6.1.0]
  - kombu [required: >=4.4.0,<5.0, installed: 4.6.4]
    - amqp [required: >=2.5.1,<3.0, installed: 2.5.1]
      - vine [required: >=1.1.3,<5.0.0a1, installed: 1.3.0]
    - importlib-metadata [required: >=0.18, installed: 0.21]
      - zipp [required: >=0.5, installed: 0.6.0]
        - more-itertools [required: Any, installed: 7.2.0]
  - pytz [required: >dev, installed: 2019.2]
  - vine [required: >=1.3.0, installed: 1.3.0]
```

IMO, it would be better to drop Celery support, since it's so simple to make your own task to send things via Celery and configure retrying and such yourself. That's what I've done in my project at least.
